# Repro_variance.ps1
# Reproduce inventory variance resolution and ledger/stock card creation.
# Usage: run from the repo root or from backend with an activated Python environment.

$backendRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $backendRoot

Write-Host "Running variance resolution reproduction from $PWD"

& python -c "from app import create_app, db; from app.models import StockCard, SuppliesLedgerCard; from app.models.inventory import InventoryItem, AuditLog; from app.models.kenya_gov_models import VarianceReport; from app.models.location_topology import Warehouse; from app.models.stock_levels import WarehouseStock; from app.models.user import User; from app.models.organization import Organization; from app.services.ledger_service import LedgerService; app=create_app('testing'); ctx=app.app_context(); ctx.push(); db.drop_all(); db.create_all(); org=Organization(id=1, name='Test Org', code='TESTORG'); db.session.add(org); db.session.commit(); user=User(organisation_id=1, username='testuser', email='test@example.com', role='employee'); user.set_password('Password1!'); db.session.add(user); db.session.commit(); item=InventoryItem(organisation_id=1, name='Item', sku='ITEM1', quantity=100, unit_price=10.0); db.session.add(item); db.session.commit(); wh=Warehouse(organisation_id=1, name='MAIN', code='MAIN', is_active=True); db.session.add(wh); db.session.commit(); ws=WarehouseStock(item_id=item.id, warehouse_id=wh.id, quantity_on_hand=100, quantity_reserved=0); db.session.add(ws); db.session.commit(); print('item.quantity', item.quantity); print('sum wh', db.session.query(db.func.sum(WarehouseStock.quantity_on_hand)).filter(WarehouseStock.item_id==item.id).scalar()); vr=VarianceReport(organization_id=1, report_number='VR-001', item_id=item.id, location_id=None, system_quantity=100, physical_quantity=92, variance=-8, reason='count mismatch'); db.session.add(vr); db.session.commit(); LedgerService.resolve_variance(vr.id, resolved_by_id=user.id); db.session.refresh(item); print('after item.quantity', item.quantity); sc=db.session.query(StockCard).filter_by(organization_id=1, item_id=item.id, location_id=None).first(); lg=db.session.query(SuppliesLedgerCard).filter_by(organization_id=1, item_id=item.id, location_id=None).first(); print('stock card exists', sc is not None, 'ledger exists', lg is not None); audit=db.session.query(AuditLog).filter_by(reference='VR-001').first(); print('audit ref exists', audit is not None); ctx.pop()"
