"""Add warehouse_id to stock_movements

Revision ID: 4f7b6456ff12
Revises: 32e4405bb5c6
Create Date: 2026-06-22 16:59:30.542326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f7b6456ff12'
down_revision: Union[str, None] = '32e4405bb5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_details_gin', table_name='audit_logs', postgresql_using='gin')
    op.alter_column('role_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('role_mappings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('stock_movements', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_index('ix_stock_movements_item_date', 'stock_movements', ['item_id', 'date'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index('ix_stock_movements_item_date', table_name='stock_movements')
    op.drop_column('stock_movements', 'warehouse_id')
    op.alter_column('role_mappings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('role_mappings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_audit_logs_details_gin', 'audit_logs', [sa.text('(details::jsonb)')], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
