"""Initial migration

Revision ID: 4f97e286b572
Revises: 
Create Date: 2026-05-08 12:10:40.727321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f97e286b572'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_organizations_active', 'organizations', ['is_active'], unique=False)
    op.create_index('ix_organizations_code', 'organizations', ['code'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_nonneg'),
    sa.CheckConstraint('reorder_level >= 0', name='ck_inventory_reorder_nonneg'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'sku', name='uq_inventory_org_sku')
    )
    op.create_index('ix_inventory_active', 'inventory_items', ['is_active'], unique=False)
    op.create_index('ix_inventory_org_id', 'inventory_items', ['organisation_id'], unique=False)
    op.create_index('ix_inventory_sku', 'inventory_items', ['sku'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'email', name='uq_user_org_email'),
    sa.UniqueConstraint('organisation_id', 'username', name='uq_user_org_username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_org_id', 'users', ['organisation_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_org_id', 'audit_logs', ['organisation_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_dept_org_code')
    )
    op.create_index('ix_departments_active', 'departments', ['is_active'], unique=False)
    op.create_index('ix_departments_head_id', 'departments', ['head_id'], unique=False)
    op.create_index('ix_departments_org_id', 'departments', ['organisation_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("type IN ('IN', 'OUT')", name='ck_stock_movement_type'),
    sa.CheckConstraint('quantity > 0', name='ck_stock_movement_qty_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_movements_date', 'stock_movements', ['date'], unique=False)
    op.create_index('ix_stock_movements_item_id', 'stock_movements', ['item_id'], unique=False)
    op.create_index('ix_stock_movements_type', 'stock_movements', ['type'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_value', sa.Float(), nullable=False),
    sa.Column('useful_life', sa.Integer(), nullable=False),
    sa.Column('depreciation_method', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('qr_code_data', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'asset_code', name='uq_asset_org_code'),
    sa.UniqueConstraint('organisation_id', 'serial_number', name='uq_asset_org_serial')
    )
    op.create_index('ix_assets_asset_code', 'assets', ['asset_code'], unique=False)
    op.create_index('ix_assets_dept_id', 'assets', ['department_id'], unique=False)
    op.create_index('ix_assets_org_id', 'assets', ['organisation_id'], unique=False)
    op.create_index('ix_assets_serial_number', 'assets', ['serial_number'], unique=False)
    op.create_index('ix_assets_status', 'assets', ['status'], unique=False)
    op.create_table('asset_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_audit_logs_action', 'asset_audit_logs', ['action'], unique=False)
    op.create_index('ix_asset_audit_logs_asset_id', 'asset_audit_logs', ['asset_id'], unique=False)
    op.create_index('ix_asset_audit_logs_created_at', 'asset_audit_logs', ['created_at'], unique=False)
    op.create_table('transfer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('from_department_id', sa.Integer(), nullable=False),
    sa.Column('to_department_id', sa.Integer(), nullable=False),
    sa.Column('requested_location', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_comments', sa.String(length=1000), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfer_requests_asset_id', 'transfer_requests', ['asset_id'], unique=False)
    op.create_index('ix_transfer_requests_from_dept', 'transfer_requests', ['from_department_id'], unique=False)
    op.create_index('ix_transfer_requests_org_id', 'transfer_requests', ['organisation_id'], unique=False)
    op.create_index('ix_transfer_requests_requested_at', 'transfer_requests', ['requested_at'], unique=False)
    op.create_index('ix_transfer_requests_requested_by', 'transfer_requests', ['requested_by'], unique=False)
    op.create_index('ix_transfer_requests_status', 'transfer_requests', ['status'], unique=False)
    op.create_index('ix_transfer_requests_to_dept', 'transfer_requests', ['to_department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfer_requests_to_dept', table_name='transfer_requests')
    op.drop_index('ix_transfer_requests_status', table_name='transfer_requests')
    op.drop_index('ix_transfer_requests_requested_by', table_name='transfer_requests')
    op.drop_index('ix_transfer_requests_requested_at', table_name='transfer_requests')
    op.drop_index('ix_transfer_requests_org_id', table_name='transfer_requests')
    op.drop_index('ix_transfer_requests_from_dept', table_name='transfer_requests')
    op.drop_index('ix_transfer_requests_asset_id', table_name='transfer_requests')
    op.drop_table('transfer_requests')
    op.drop_index('ix_asset_audit_logs_created_at', table_name='asset_audit_logs')
    op.drop_index('ix_asset_audit_logs_asset_id', table_name='asset_audit_logs')
    op.drop_index('ix_asset_audit_logs_action', table_name='asset_audit_logs')
    op.drop_table('asset_audit_logs')
    op.drop_index('ix_assets_status', table_name='assets')
    op.drop_index('ix_assets_serial_number', table_name='assets')
    op.drop_index('ix_assets_org_id', table_name='assets')
    op.drop_index('ix_assets_dept_id', table_name='assets')
    op.drop_index('ix_assets_asset_code', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index('ix_stock_movements_type', table_name='stock_movements')
    op.drop_index('ix_stock_movements_item_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_date', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_departments_org_id', table_name='departments')
    op.drop_index('ix_departments_head_id', table_name='departments')
    op.drop_index('ix_departments_active', table_name='departments')
    op.drop_table('departments')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_org_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_inventory_sku', table_name='inventory_items')
    op.drop_index('ix_inventory_org_id', table_name='inventory_items')
    op.drop_index('ix_inventory_active', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('ix_organizations_code', table_name='organizations')
    op.drop_index('ix_organizations_active', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
