"""add logo and preferences

Revision ID: 7ae1ef9507ee
Revises: 82d1482e2017
Create Date: 2026-05-10 09:40:14.405875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae1ef9507ee'
down_revision: Union[str, None] = '82d1482e2017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.drop_table('suppliers')
    op.add_column('assets', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('bin_id', sa.Integer(), nullable=True))
    op.alter_column('assets', 'purchase_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('assets', 'current_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'assets', 'warehouses', ['warehouse_id'], ['id'])
    op.create_foreign_key(None, 'assets', 'warehouse_bins', ['bin_id'], ['id'])
    op.alter_column('inventory_items', 'unit_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=512), nullable=True))
    op.add_column('organizations', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('transfer_requests', sa.Column('to_warehouse_id', sa.Integer(), nullable=True))
    op.add_column('transfer_requests', sa.Column('to_bin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_requests', 'warehouse_bins', ['to_bin_id'], ['id'])
    op.create_foreign_key(None, 'transfer_requests', 'warehouses', ['to_warehouse_id'], ['id'])
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=120), nullable=True))
    op.create_index('ix_warehouse_bins_shelf_status', 'warehouse_bins', ['shelf_id', 'status'], unique=False)
    op.create_index('ix_warehouse_bins_status', 'warehouse_bins', ['status'], unique=False)
    op.create_index('ix_warehouses_org_id', 'warehouses', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_warehouses_org_id', table_name='warehouses')
    op.drop_index('ix_warehouse_bins_status', table_name='warehouse_bins')
    op.drop_index('ix_warehouse_bins_shelf_status', table_name='warehouse_bins')
    op.drop_column('users', 'department')
    op.drop_column('users', 'phone_number')
    op.drop_constraint(None, 'transfer_requests', type_='foreignkey')
    op.drop_constraint(None, 'transfer_requests', type_='foreignkey')
    op.drop_column('transfer_requests', 'to_bin_id')
    op.drop_column('transfer_requests', 'to_warehouse_id')
    op.drop_column('organizations', 'preferences')
    op.drop_column('organizations', 'logo_url')
    op.alter_column('inventory_items', 'unit_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.alter_column('assets', 'current_value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('assets', 'purchase_value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('assets', 'bin_id')
    op.drop_column('assets', 'warehouse_id')
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('average_lead_time_days', sa.INTEGER(), nullable=True),
    sa.Column('reliability_score', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_supplier_code')
    )
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_table('system_events')
    # ### end Alembic commands ###
