"""Add inventory transfers

Revision ID: 7b78fb2f3dda
Revises: 7ae1ef9507ee
Create Date: 2026-05-18 21:18:16.016691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b78fb2f3dda'
down_revision: Union[str, None] = '7ae1ef9507ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_inventory_low_stock_query', 'inventory_items', ['organisation_id', 'is_active', 'quantity', 'reorder_level'], unique=False)
    op.create_index('ix_restock_alerts_org_severity', 'restock_alerts', ['organisation_id', 'severity', 'status'], unique=False)
    
    with op.batch_alter_table('transfer_requests') as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=50), nullable=False, server_default='ASSET'))
        batch_op.add_column(sa.Column('inventory_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.alter_column('asset_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('from_department_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_foreign_key('fk_transfer_to_warehouse', 'warehouses', ['to_warehouse_id'], ['id'])
        batch_op.create_foreign_key('fk_transfer_to_bin', 'warehouse_bins', ['to_bin_id'], ['id'])
        batch_op.create_foreign_key('fk_transfer_inventory', 'inventory_items', ['inventory_item_id'], ['id'])

    op.create_index('ix_transfer_requests_inventory_id', 'transfer_requests', ['inventory_item_id'], unique=False)
    op.create_index('ix_transfer_requests_item_type', 'transfer_requests', ['item_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_requests', type_='foreignkey')
    op.drop_constraint(None, 'transfer_requests', type_='foreignkey')
    op.drop_constraint(None, 'transfer_requests', type_='foreignkey')
    op.drop_index('ix_transfer_requests_item_type', table_name='transfer_requests')
    op.drop_index('ix_transfer_requests_inventory_id', table_name='transfer_requests')
    op.alter_column('transfer_requests', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transfer_requests', 'to_bin_id')
    op.drop_column('transfer_requests', 'to_warehouse_id')
    op.drop_column('transfer_requests', 'quantity')
    op.drop_column('transfer_requests', 'inventory_item_id')
    op.drop_column('transfer_requests', 'item_type')
    op.drop_index('ix_restock_alerts_org_severity', table_name='restock_alerts')
    op.drop_index('ix_inventory_low_stock_query', table_name='inventory_items')
    pass
    # ### end Alembic commands ###
