"""Add spatial coordinates and environment imagery to bins

Revision ID: a8bf43f2b3f3
Revises: 3d88a155fd9f
Create Date: 2026-05-08 12:36:28.049940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8bf43f2b3f3'
down_revision: Union[str, None] = '3d88a155fd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_bins', sa.Column('x_pos', sa.Float(), nullable=True))
    op.add_column('warehouse_bins', sa.Column('y_pos', sa.Float(), nullable=True))
    op.add_column('warehouse_bins', sa.Column('z_pos', sa.Float(), nullable=True))
    op.add_column('warehouse_bins', sa.Column('environment_image_url', sa.String(length=500), nullable=True))
    op.add_column('warehouse_bins', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_bins', 'description')
    op.drop_column('warehouse_bins', 'environment_image_url')
    op.drop_column('warehouse_bins', 'z_pos')
    op.drop_column('warehouse_bins', 'y_pos')
    op.drop_column('warehouse_bins', 'x_pos')
    # ### end Alembic commands ###
