"""Add asset_id and item_type columns to goods_receipt_items

Revision ID: add_asset_support_grn
Revises: ef332df3c6b4, 06_add_warehouse_id_inventory, add_employee_item_tracking
Create Date: 2026-07-07 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_asset_support_grn'
down_revision = ('ef332df3c6b4', '06_add_warehouse_id_inventory', 'add_employee_item_tracking')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_receipt_items', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column('goods_receipt_items', sa.Column('item_type', sa.String(length=50), nullable=True, server_default='inventory'))
    
    # Add foreign key constraint for asset_id
    op.create_foreign_key(None, 'goods_receipt_items', 'assets', ['asset_id'], ['id'])
    
    # Update existing rows to have item_type = 'inventory' (the default)
    op.execute("UPDATE goods_receipt_items SET item_type = 'inventory' WHERE item_type IS NULL")
    
    # Make item_type non-nullable after backfill
    op.alter_column('goods_receipt_items', 'item_type',
               existing_type=sa.String(length=50),
               nullable=False,
               server_default='inventory')
    
    # Make item_id nullable to support asset-only GRNs
    op.alter_column('goods_receipt_items', 'item_id',
               existing_type=sa.Integer(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods_receipt_items', 'item_id',
               existing_type=sa.Integer(),
               nullable=False)
    op.alter_column('goods_receipt_items', 'item_type',
               existing_type=sa.String(length=50),
               nullable=True,
               server_default=None)
    op.drop_constraint(None, 'goods_receipt_items', type_='foreignkey')
    op.drop_column('goods_receipt_items', 'item_type')
    op.drop_column('goods_receipt_items', 'asset_id')
    # ### end Alembic commands ###
